# Generated by Django 5.1.7 on 2025-03-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Restaurant', 'Restaurant'), ('Healthcare', 'Healthcare')], max_length=50),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.user'),
        ),
    ]
