# Generated by Django 5.1.7 on 2025-03-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_task_queue_estimated_wait_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='alternative_suggestion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Restaurant', 'Restaurant'), ('Healthcare', 'Healthcare'), ('School', 'School')], max_length=50),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
